# Data Preprocessing

Import libraries and paths

In [1]:
import os
import numpy as np
import pandas as pd

from IPython.display import display

# Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Project paths
BASE_DIR = "/content/drive/MyDrive/ML Assignment"
SPLIT_DIR = os.path.join(BASE_DIR, "splitted_dataset")

print("Project directory:", BASE_DIR)
print("Split directory:", SPLIT_DIR)
print("Files:", os.listdir(SPLIT_DIR))

Mounted at /content/drive
Project directory: /content/drive/MyDrive/ML Assignment
Split directory: /content/drive/MyDrive/ML Assignment/splitted_dataset
Files: ['train.csv', 'validation.csv', 'test.csv']

Load Splitted datasets

In [2]:
train_df = pd.read_csv(
    os.path.join(SPLIT_DIR, "train.csv")
)

val_df = pd.read_csv(
    os.path.join(SPLIT_DIR, "validation.csv")
)

test_df = pd.read_csv(
    os.path.join(SPLIT_DIR, "test.csv")
)

print("Training shape   :", train_df.shape)
print("Validation shape :", val_df.shape)
print("Test shape       :", test_df.shape)

Training shape   : (18183, 121)
Validation shape : (3873, 121)
Test shape       : (3923, 121)

In [3]:
# Preserve match IDs separately for safe alignment in feature engineering

train_ids = train_df["id"].copy()
val_ids = val_df["id"].copy()
test_ids = test_df["id"].copy()

# Verify IDs are valid
assert train_ids.is_unique, "Duplicate match IDs found in training data."
assert val_ids.is_unique, "Duplicate match IDs found in validation data."
assert test_ids.is_unique, "Duplicate match IDs found in test data."

assert len(train_ids) == len(train_df)
assert len(val_ids) == len(val_df)
assert len(test_ids) == len(test_df)

print("Match IDs preserved successfully.")
print("Training IDs   :", len(train_ids))
print("Validation IDs :", len(val_ids))
print("Test IDs       :", len(test_ids))

Match IDs preserved successfully.
Training IDs   : 18183
Validation IDs : 3873
Test IDs       : 3923

Verify the target

In [4]:
TARGET = "target_outcome"

print("Target column:", TARGET)

for name, df in [
    ("Training", train_df),
    ("Validation", val_df),
    ("Test", test_df)
]:
    print(f"\n{name} target distribution:")
    display(
        df[TARGET]
        .value_counts()
        .rename_axis("Outcome")
        .reset_index(name="Count")
    )

Target column: target_outcome

Training target distribution:

    Outcome  Count
0  Home Win   8433
1  Away Win   5126
2      Draw   4624

Validation target distribution:

    Outcome  Count
0  Home Win   1753
1  Away Win   1147
2      Draw    973

Test target distribution:

    Outcome  Count
0  Home Win   1731
1  Away Win   1193
2      Draw    999

Verify chronological split

In [5]:
for name, df in [
    ("Training", train_df),
    ("Validation", val_df),
    ("Test", test_df)
]:
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

    print(f"{name}:")
    print("  Start:", df["date"].min())
    print("  End  :", df["date"].max())

Training:
  Start: 2008-07-18 00:00:00
  End  : 2014-02-10 00:00:00
Validation:
  Start: 2014-02-11 00:00:00
  End  : 2015-04-10 00:00:00
Test:
  Start: 2015-04-11 00:00:00
  End  : 2016-05-25 00:00:00

In [6]:
print(
    "Training end < Validation start:",
    train_df["date"].max() <= val_df["date"].min()
)

print(
    "Validation end < Test start:",
    val_df["date"].max() <= test_df["date"].min()
)

Training end < Validation start: True
Validation end < Test start: True

In [7]:
for boundary_date in [
    val_df["date"].min(),
    test_df["date"].min()
]:
    print("=" * 60)
    print("Boundary date:", boundary_date)

    print(
        "Training:",
        (train_df["date"] == boundary_date).sum()
    )

    print(
        "Validation:",
        (val_df["date"] == boundary_date).sum()
    )

    print(
        "Test:",
        (test_df["date"] == boundary_date).sum()
    )

============================================================
Boundary date: 2014-02-11 00:00:00
Training: 0
Validation: 6
Test: 0
============================================================
Boundary date: 2015-04-11 00:00:00
Training: 0
Validation: 0
Test: 38

Create explicit leakage list

In [8]:
LEAKAGE_COLUMNS = [
    "home_team_goal",
    "away_team_goal",
    "target_outcome",
    "total_goals",
    "goal_difference"
]

print("Leakage columns:")
for col in LEAKAGE_COLUMNS:
    print("-", col)

Leakage columns:
- home_team_goal
- away_team_goal
- target_outcome
- total_goals
- goal_difference

Identify non-predictive columns

In [9]:
id_columns = [
    col for col in train_df.columns
    if col.lower() == "id"
    or col.lower().endswith("_id")
    or col.lower().endswith("_api_id")
]

print("Potential identifier columns:")
for col in id_columns:
    print("-", col)

Potential identifier columns:
- id
- country_id
- league_id
- match_api_id
- home_team_api_id
- away_team_api_id
- match_id

In [10]:
id_summary = []

for col in id_columns:
    id_summary.append({
        "Column": col,
        "Unique Values": train_df[col].nunique(),
        "Training Rows": len(train_df),
        "Unique Ratio": round(train_df[col].nunique() / len(train_df), 4)
    })

display(pd.DataFrame(id_summary))

             Column  Unique Values  Training Rows  Unique Ratio
0                id          18183          18183        1.0000
1        country_id             11          18183        0.0006
2         league_id             11          18183        0.0006
3      match_api_id          18183          18183        1.0000
4  home_team_api_id            274          18183        0.0151
5  away_team_api_id            274          18183        0.0151
6          match_id          18183          18183        1.0000

In [11]:
IDENTIFIER_COLUMNS = [
    "id",
    "match_id",
    "country_id",
    "league_id",
    "match_api_id",
    "home_team_api_id",
    "away_team_api_id"
]

IDENTIFIER_COLUMNS = [
    col for col in IDENTIFIER_COLUMNS
    if col in train_df.columns
]

print("Identifiers selected for removal:")
for col in IDENTIFIER_COLUMNS:
    print("-", col)

Identifiers selected for removal:
- id
- match_id
- country_id
- league_id
- match_api_id
- home_team_api_id
- away_team_api_id

Create preprocessing exclusion list

In [12]:
EXCLUDE_COLUMNS = sorted(
    set(LEAKAGE_COLUMNS + IDENTIFIER_COLUMNS)
    .intersection(train_df.columns)
)

print("Total columns excluded:", len(EXCLUDE_COLUMNS))

for col in EXCLUDE_COLUMNS:
    print("-", col)

Total columns excluded: 10
- away_team_api_id
- away_team_goal
- country_id
- home_team_api_id
- home_team_goal
- id
- league_id
- match_api_id
- match_id
- target_outcome

Create working datasets

In [13]:
X_train_raw = train_df.drop(columns=EXCLUDE_COLUMNS).copy()
X_val_raw = val_df.drop(columns=EXCLUDE_COLUMNS).copy()
X_test_raw = test_df.drop(columns=EXCLUDE_COLUMNS).copy()

print("Training:", X_train_raw.shape)
print("Validation:", X_val_raw.shape)
print("Test:", X_test_raw.shape)

Training: (18183, 111)
Validation: (3873, 111)
Test: (3923, 111)

In [14]:
# Separately store y
y_train = train_df[TARGET].copy()
y_val = val_df[TARGET].copy()
y_test = test_df[TARGET].copy()

print("X_train:", X_train_raw.shape)
print("y_train:", y_train.shape)

X_train: (18183, 111)
y_train: (18183,)

Check remaining columns

In [15]:
column_summary = pd.DataFrame({
    "Column": X_train_raw.columns,
    "Data Type": X_train_raw.dtypes.astype(str),
    "Missing Values": X_train_raw.isnull().sum().values,
    "Missing %": (
        X_train_raw.isnull().mean() * 100
    ).round(2).values,
    "Unique Values": X_train_raw.nunique().values
})

display(column_summary)

,Column,Data Type,Missing Values,Missing %,Unique Values
season,season,object,0,0.00,6
stage,stage,int64,0,0.00,38
date,date,datetime64[ns],0,0.00,1198
home_player_X1,home_player_X1,float64,1821,10.01,3
home_player_X2,home_player_X2,float64,1821,10.01,8
...,...,...,...,...,...
BSA,BSA,float64,4022,22.12,96
league_name,league_name,object,0,0.00,11
country_name,country_name,object,0,0.00,11
home_team,home_team,object,0,0.00,272
away_team,away_team,object,0,0.00,272

Missing-value assessment

In [16]:
def missing_report(df, name):
    result = pd.DataFrame({
        "Column": df.columns,
        "Missing Values": df.isnull().sum().values,
        "Missing %": (df.isnull().mean() * 100).round(2).values
    })

    result = result[result["Missing Values"] > 0]
    result = result.sort_values("Missing %", ascending=False)

    print(f"\n{name} missing-value report")
    display(result)

missing_report(X_train_raw, "Training")
missing_report(X_val_raw, "Validation")
missing_report(X_test_raw, "Test")

Training missing-value report

           Column  Missing Values  Missing %
91            PSA           13779      75.78
90            PSD           13779      75.78
89            PSH           13779      75.78
69           goal            8929      49.11
73           card            8929      49.11
..            ...             ...        ...
55  home_player_9            1247       6.86
58  away_player_1            1219       6.70
47  home_player_1            1210       6.65
64  away_player_7            1205       6.63
53  home_player_7            1200       6.60

[104 rows x 3 columns]

Validation missing-value report

             Column  Missing Values  Missing %
101             GBH            3873     100.00
102             GBD            3873     100.00
106             BSA            3873     100.00
105             BSD            3873     100.00
103             GBA            3873     100.00
104             BSH            3873     100.00
96              SJD            2562      66.15
97              SJA            2562      66.15
95              SJH            2562      66.15
73             card            1557      40.20
72       foulcommit            1557      40.20
74            cross            1557      40.20
70           shoton            1557      40.20
69             goal            1557      40.20
75           corner            1557      40.20
71          shotoff            1557      40.20
76       possession            1557      40.20
84              IWD             525      13.56
83              IWH             525      13.56
85              IWA             525      13.56
90              PSD             521      13.45
89              PSH             521      13.45
91              PSA             521      13.45
86              LBH             516      13.32
88              LBA             516      13.32
87              LBD             516      13.32
94              WHA             509      13.14
92              WHH             509      13.14
93              WHD             509      13.14
80              BWH             507      13.09
79            B365A             507      13.09
78            B365D             507      13.09
81              BWD             507      13.09
98              VCH             507      13.09
77            B365H             507      13.09
82              BWA             507      13.09
99              VCD             507      13.09
100             VCA             507      13.09
57   home_player_11              50       1.29
68   away_player_11              49       1.27
56   home_player_10              32       0.83
50    home_player_4              28       0.72
67   away_player_10              27       0.70
61    away_player_4              25       0.65
66    away_player_9              21       0.54
52    home_player_6              18       0.46
64    away_player_7              18       0.46
63    away_player_6              16       0.41
60    away_player_3              15       0.39
62    away_player_5              15       0.39
65    away_player_8              14       0.36
54    home_player_8              13       0.34
51    home_player_5              13       0.34
55    home_player_9              12       0.31
49    home_player_3              12       0.31
53    home_player_7              12       0.31
48    home_player_2               6       0.15
47    home_player_1               5       0.13
59    away_player_2               5       0.13
58    away_player_1               4       0.10

Test missing-value report

             Column  Missing Values  Missing %
103             GBA            3923     100.00
104             BSH            3923     100.00
101             GBH            3923     100.00
96              SJD            3923     100.00
106             BSA            3923     100.00
97              SJA            3923     100.00
95              SJH            3923     100.00
105             BSD            3923     100.00
102             GBD            3923     100.00
73             card            1276      32.53
72       foulcommit            1276      32.53
74            cross            1276      32.53
70           shoton            1276      32.53
69             goal            1276      32.53
75           corner            1276      32.53
71          shotoff            1276      32.53
76       possession            1276      32.53
84              IWD             513      13.08
83              IWH             513      13.08
85              IWA             513      13.08
90              PSD             511      13.03
89              PSH             511      13.03
91              PSA             511      13.03
88              LBA             503      12.82
98              VCH             503      12.82
99              VCD             503      12.82
86              LBH             503      12.82
100             VCA             503      12.82
87              LBD             503      12.82
82              BWA             502      12.80
81              BWD             502      12.80
80              BWH             502      12.80
78            B365D             501      12.77
93              WHD             501      12.77
79            B365A             501      12.77
77            B365H             501      12.77
94              WHA             501      12.77
92              WHH             501      12.77
57   home_player_11              37       0.94
68   away_player_11              35       0.89
56   home_player_10              34       0.87
67   away_player_10              34       0.87
50    home_player_4              26       0.66
65    away_player_8              23       0.59
63    away_player_6              20       0.51
48    home_player_2              19       0.48
61    away_player_4              18       0.46
59    away_player_2              16       0.41
51    home_player_5              16       0.41
66    away_player_9              16       0.41
53    home_player_7              15       0.38
52    home_player_6              15       0.38
62    away_player_5              15       0.38
55    home_player_9              14       0.36
54    home_player_8              13       0.33
60    away_player_3              13       0.33
64    away_player_7              12       0.31
58    away_player_1              11       0.28
47    home_player_1               9       0.23
49    home_player_3               8       0.20

Compare missing-value patterns

In [17]:
missing_comparison = pd.DataFrame({
    "Training Missing": X_train_raw.isnull().sum(),
    "Validation Missing": X_val_raw.isnull().sum(),
    "Test Missing": X_test_raw.isnull().sum()
})

missing_comparison["Total Missing"] = (
    missing_comparison["Training Missing"]
    + missing_comparison["Validation Missing"]
    + missing_comparison["Test Missing"]
)

display(
    missing_comparison.sort_values(
        "Total Missing",
        ascending=False
    )
)

,Training Missing,Validation Missing,Test Missing,Total Missing
PSH,13779,521,511,14811
PSD,13779,521,511,14811
PSA,13779,521,511,14811
BSD,4022,3873,3923,11818
BSH,4022,3873,3923,11818
...,...,...,...,...
stage,0,0,0,0
league_name,0,0,0,0
country_name,0,0,0,0
home_team,0,0,0,0
away_team,0,0,0,0

Check categorical variables

In [18]:
categorical_columns = X_train_raw.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numerical_columns = X_train_raw.select_dtypes(
    include=np.number
).columns.tolist()

print("Categorical columns:", len(categorical_columns))
print(categorical_columns)

print("\nNumerical columns:", len(numerical_columns))
print(numerical_columns)

Categorical columns: 13
['season', 'goal', 'shoton', 'shotoff', 'foulcommit', 'card', 'cross', 'corner', 'possession', 'league_name', 'country_name', 'home_team', 'away_team']

Numerical columns: 97
['stage', 'home_player_X1', 'home_player_X2', 'home_player_X3', 'home_player_X4', 'home_player_X5', 'home_player_X6', 'home_player_X7', 'home_player_X8', 'home_player_X9', 'home_player_X10', 'home_player_X11', 'away_player_X1', 'away_player_X2', 'away_player_X3', 'away_player_X4', 'away_player_X5', 'away_player_X6', 'away_player_X7', 'away_player_X8', 'away_player_X9', 'away_player_X10', 'away_player_X11', 'home_player_Y1', 'home_player_Y2', 'home_player_Y3', 'home_player_Y4', 'home_player_Y5', 'home_player_Y6', 'home_player_Y7', 'home_player_Y8', 'home_player_Y9', 'home_player_Y10', 'home_player_Y11', 'away_player_Y1', 'away_player_Y2', 'away_player_Y3', 'away_player_Y4', 'away_player_Y5', 'away_player_Y6', 'away_player_Y7', 'away_player_Y8', 'away_player_Y9', 'away_player_Y10', 'away_player_Y11', 'home_player_1', 'home_player_2', 'home_player_3', 'home_player_4', 'home_player_5', 'home_player_6', 'home_player_7', 'home_player_8', 'home_player_9', 'home_player_10', 'home_player_11', 'away_player_1', 'away_player_2', 'away_player_3', 'away_player_4', 'away_player_5', 'away_player_6', 'away_player_7', 'away_player_8', 'away_player_9', 'away_player_10', 'away_player_11', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA']

Check categorical consistency

In [19]:
for col in categorical_columns:
    print("=" * 80)
    print("COLUMN:", col)
    print("Training unique:", X_train_raw[col].nunique())
    print("Validation unique:", X_val_raw[col].nunique())
    print("Test unique:", X_test_raw[col].nunique())

    print("\nSample training values:")
    print(X_train_raw[col].dropna().unique()[:20])

================================================================================
COLUMN: season
Training unique: 6
Validation unique: 2
Test unique: 2

Sample training values:
['2008/2009' '2009/2010' '2010/2011' '2011/2012' '2012/2013' '2013/2014']
================================================================================
COLUMN: goal
Training unique: 8591
Validation unique: 2157
Test unique: 2479

Sample training values:
['<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>12</elapsed><player1>30872</player1><sortorder>0</sortorder><team>9823</team><id>375301</id><n>21</n><type>goal</type><goal_type>n</goal_type></value><value><comment>p</comment><stats><penalties>1</penalties></stats><event_incident_typefk>20</event_incident_typefk><elapsed>16</elapsed><player1>32118</player1><sortorder>0</sortorder><team>9823</team><id>375302</id><n>22</n><type>goal</type><goal_type>p</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>25</elapsed><player1>33101</player1><sortorder>0</sortorder><team>9790</team><id>375303</id><n>20</n><type>goal</type><goal_type>n</goal_type></value><value><comment>p</comment><stats><penalties>1</penalties></stats><event_incident_typefk>20</event_incident_typefk><elapsed>56</elapsed><player1>39106</player1><sortorder>0</sortorder><team>9790</team><id>375308</id><n>23</n><type>goal</type><goal_type>p</goal_type></value></goal>'
 '<goal><value><comment>dg</comment><event_incident_typefk>299</event_incident_typefk><elapsed>32</elapsed><subtype>header</subtype><player1>24166</player1><sortorder>1</sortorder><team>8549</team><id>376536</id><n>76</n><type>goal</type><goal_type>dg</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>71</elapsed><player2>35608</player2><subtype>shot</subtype><player1>24166</player1><sortorder>7</sortorder><team>8549</team><id>377347</id><n>338</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>86</elapsed><player2>33128</player2><subtype>shot</subtype><player1>38491</player1><sortorder>3</sortorder><team>8549</team><id>377556</id><n>355</n><type>goal</type><goal_type>n</goal_type></value><value><comment>o</comment><stats><owngoals>1</owngoals></stats><elapsed_plus>3</elapsed_plus><event_incident_typefk>115</event_incident_typefk><elapsed>90</elapsed><player1>38899</player1><sortorder>1</sortorder><team>8549</team><id>377648</id><n>366</n><type>goal</type><goal_type>o</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>407</event_incident_typefk><elapsed>22</elapsed><player2>23916</player2><subtype>distance</subtype><player1>30342</player1><sortorder>0</sortorder><team>8655</team><id>376354</id><n>252</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><elapsed_plus>2</elapsed_plus><event_incident_typefk>130</event_incident_typefk><elapsed>45</elapsed><subtype>direct_freekick</subtype><player1>24011</player1><sortorder>0</sortorder><team>8668</team><id>376795</id><n>277</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>65</elapsed><player2>24011</player2><subtype>header</subtype><player1>24160</player1><sortorder>0</sortorder><team>8668</team><id>377232</id><n>305</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>67</elapsed><player2>24136</player2><subtype>shot</subtype><player1>30646</player1><sortorder>0</sortorder><team>8655</team><id>377255</id><n>297</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><elapsed_plus>5</elapsed_plus><event_incident_typefk>393</event_incident_typefk><elapsed>90</elapsed><player2>23921</player2><subtype>shot</subtype><player1>37764</player1><sortorder>1</sortorder><team>8655</team><id>377671</id><n>320</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>4</elapsed><player2>36394</player2><subtype>shot</subtype><player1>23139</player1><sortorder>2</sortorder><team>8654</team><id>376060</id><n>244</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>10</elapsed><player2>37277</player2><subtype>shot</subtype><player1>23139</player1><sortorder>1</sortorder><team>8654</team><id>376165</id><n>251</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>411</event_incident_typefk><elapsed>47</elapsed><player2>34466</player2><subtype>volley</subtype><player1>127857</player1><sortorder>3</sortorder><team>8528</team><id>376929</id><n>294</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>407</event_incident_typefk><elapsed>83</elapsed><player2>30889</player2><subtype>distance</subtype><player1>30853</player1><sortorder>0</sortorder><team>8650</team><id>378041</id><n>344</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>407</event_incident_typefk><elapsed>34</elapsed><player2>23933</player2><subtype>distance</subtype><player1>26454</player1><sortorder>0</sortorder><team>8559</team><id>376569</id><n>298</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>41</elapsed><player2>23783</player2><subtype>header</subtype><player1>23934</player1><sortorder>2</sortorder><team>8559</team><id>376692</id><n>303</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><elapsed_plus>2</elapsed_plus><event_incident_typefk>406</event_incident_typefk><elapsed>45</elapsed><player2>23931</player2><subtype>header</subtype><player1>34261</player1><sortorder>2</sortorder><team>8559</team><id>376818</id><n>311</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><elapsed_plus>3</elapsed_plus><event_incident_typefk>406</event_incident_typefk><elapsed>90</elapsed><player2>23371</player2><subtype>header</subtype><player1>38755</player1><sortorder>4</sortorder><team>10194</team><id>377666</id><n>362</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>4</elapsed><player2>39297</player2><subtype>shot</subtype><player1>26181</player1><sortorder>2</sortorder><team>9825</team><id>375546</id><n>231</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>2</elapsed><player1>27301</player1><sortorder>0</sortorder><team>10189</team><id>375872</id><n>18</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>7</elapsed><player1>30249</player1><sortorder>0</sortorder><team>10189</team><id>375899</id><n>19</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>64</elapsed><player1>30249</player1><sortorder>0</sortorder><team>10189</team><id>376839</id><n>23</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>411</event_incident_typefk><elapsed>61</elapsed><player2>37550</player2><subtype>volley</subtype><player1>30827</player1><sortorder>0</sortorder><team>8697</team><id>376803</id><n>282</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>131</event_incident_typefk><elapsed>74</elapsed><subtype>loose_ball</subtype><player1>30266</player1><sortorder>0</sortorder><team>9912</team><id>376871</id><n>294</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>407</event_incident_typefk><elapsed>80</elapsed><player2>35996</player2><subtype>distance</subtype><player1>30827</player1><sortorder>1</sortorder><team>8697</team><id>376930</id><n>301</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>80</event_incident_typefk><elapsed>82</elapsed><subtype>shot</subtype><player1>30266</player1><sortorder>1</sortorder><team>9912</team><id>376956</id><n>303</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>9</elapsed><player2>24843</player2><subtype>header</subtype><player1>34248</player1><sortorder>1</sortorder><team>9879</team><id>376153</id><n>231</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>407</event_incident_typefk><elapsed>23</elapsed><player2>34430</player2><subtype>distance</subtype><player1>39073</player1><sortorder>1</sortorder><team>8667</team><id>376379</id><n>243</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>82</elapsed><player2>23034</player2><subtype>shot</subtype><player1>23563</player1><sortorder>1</sortorder><team>8667</team><id>377500</id><n>295</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>4</elapsed><player1>31718</player1><sortorder>0</sortorder><team>9789</team><id>375884</id><n>23</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>21</elapsed><player1>27556</player1><sortorder>0</sortorder><team>8178</team><id>375981</id><n>24</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>36</elapsed><player1>27363</player1><sortorder>0</sortorder><team>9789</team><id>376199</id><n>28</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>49</elapsed><player1>71399</player1><sortorder>0</sortorder><team>9789</team><id>376626</id><n>22</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>83</elapsed><player1>31199</player1><sortorder>0</sortorder><team>8178</team><id>377065</id><n>29</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>20</elapsed><player1>38848</player1><sortorder>0</sortorder><team>8722</team><id>375977</id><n>17</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>48</elapsed><player1>27324</player1><sortorder>0</sortorder><team>8721</team><id>376609</id><n>18</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>78</elapsed><player1>39902</player1><sortorder>0</sortorder><team>8721</team><id>376937</id><n>20</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>30</elapsed><player1>37381</player1><sortorder>0</sortorder><team>8295</team><id>376024</id><n>19</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>16</elapsed><player1>36084</player1><sortorder>0</sortorder><team>8226</team><id>375972</id><n>21</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>54</elapsed><player1>35411</player1><sortorder>0</sortorder><team>8226</team><id>376725</id><n>22</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>76</elapsed><player1>36084</player1><sortorder>0</sortorder><team>8226</team><id>376938</id><n>23</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>44</elapsed><player1>25819</player1><sortorder>0</sortorder><team>8177</team><id>379206</id><n>15</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>60</elapsed><player1>36130</player1><sortorder>0</sortorder><team>8177</team><id>379412</id><n>16</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>47</elapsed><player2>23354</player2><subtype>header</subtype><player1>26165</player1><sortorder>2</sortorder><team>10252</team><id>378837</id><n>251</n><type>goal</type><goal_type>n</goal_type></value><value><comment>p</comment><stats><penalties>1</penalties></stats><event_incident_typefk>20</event_incident_typefk><elapsed>64</elapsed><player1>40198</player1><sortorder>0</sortorder><team>8456</team><id>378981</id><n>266</n><type>goal</type><goal_type>p</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>69</elapsed><player2>24658</player2><subtype>shot</subtype><player1>23264</player1><sortorder>1</sortorder><team>10252</team><id>379030</id><n>270</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>74</elapsed><player2>23782</player2><subtype>header</subtype><player1>23264</player1><sortorder>1</sortorder><team>10252</team><id>379074</id><n>283</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>76</elapsed><player2>23782</player2><subtype>shot</subtype><player1>23264</player1><sortorder>1</sortorder><team>10252</team><id>379095</id><n>277</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>90</elapsed><player2>45431</player2><subtype>shot</subtype><player1>46403</player1><sortorder>1</sortorder><team>8456</team><id>379250</id><n>281</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>15</elapsed><player1>30628</player1><sortorder>0</sortorder><team>10269</team><id>378917</id><n>21</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>26</elapsed><player1>40203</player1><sortorder>0</sortorder><team>10269</team><id>379040</id><n>22</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>44</elapsed><player1>27326</player1><sortorder>0</sortorder><team>10269</team><id>379196</id><n>25</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>60</elapsed><player1>31936</player1><sortorder>0</sortorder><team>9788</team><id>379399</id><n>27</n><type>goal</type><goal_type>n</goal_type></value></goal>'
 '<goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>22</elapsed><player2>38807</player2><subtype>header</subtype><player1>37799</player1><sortorder>5</sortorder><team>10261</team><id>378998</id><n>295</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>24</elapsed><player2>24154</player2><subtype>shot</subtype><player1>24148</player1><sortorder>4</sortorder><team>10260</team><id>379019</id><n>298</n><type>goal</type><goal_type>n</goal_type></value></goal>'

Check numeric columns for impossible values

In [20]:
numeric_summary = X_train_raw[numerical_columns].describe().T

numeric_summary["Missing"] = X_train_raw[numerical_columns].isnull().sum()

display(numeric_summary)

,count,mean,std,min,25%,50%,75%,max,Missing
stage,18183.0,17.523181,10.253143,1.00,9.00,17.0,26.00,38.0,0
home_player_X1,16362.0,0.999389,0.027075,0.00,1.00,1.0,1.00,2.0,1821
home_player_X2,16362.0,2.052255,0.304834,0.00,2.00,2.0,2.00,8.0,1821
home_player_X3,16351.0,4.037368,0.306122,2.00,4.00,4.0,4.00,8.0,1832
home_player_X4,16351.0,6.059385,0.364422,2.00,6.00,6.0,6.00,8.0,1832
...,...,...,...,...,...,...,...,...,...
GBD,14162.0,3.648189,0.867440,1.45,3.20,3.3,3.75,11.0,4021
GBA,14162.0,4.353097,3.010189,1.12,2.50,3.4,5.00,34.0,4021
BSH,14161.0,2.497894,1.507793,1.04,1.67,2.1,2.62,17.0,4022
BSD,14161.0,3.660742,0.868272,1.33,3.25,3.4,3.75,13.0,4022
BSA,14161.0,4.405663,3.189814,1.12,2.50,3.4,5.00,34.0,4022

Date consistency

In [21]:
for df in [X_train_raw, X_val_raw, X_test_raw]:
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

print("Missing dates:")
print("Train:", X_train_raw["date"].isna().sum())
print("Validation:", X_val_raw["date"].isna().sum())
print("Test:", X_test_raw["date"].isna().sum())

Missing dates:
Train: 0
Validation: 0
Test: 0

Missing-value handling

In [22]:
# Copy datasets
X_train = X_train_raw.copy()
X_val = X_val_raw.copy()
X_test = X_test_raw.copy()

# Define all 10 bookmaker odds columns to exclude from raw median imputation
BOOKMAKER_TRIPLETS = {
    "B365": ("B365H", "B365D", "B365A"),
    "BW":   ("BWH",   "BWD",   "BWA"),
    "IW":   ("IWH",   "IWD",   "IWA"),
    "LB":   ("LBH",   "LBD",   "LBA"),
    "PS":   ("PSH",   "PSD",   "PSA"),
    "WH":   ("WHH",   "WHD",   "WHA"),
    "SJ":   ("SJH",   "SJD",   "SJA"),
    "VC":   ("VCH",   "VCD",   "VCA"),
    "GB":   ("GBH",   "GBD",   "GBA"),
    "BS":   ("BSH",   "BSD",   "BSA"),
}
ODDS_COLS = [c for t in BOOKMAKER_TRIPLETS.values() for c in t]

# Numerical columns (EXCLUDING raw odds)
numeric_columns = [
    c for c in X_train.select_dtypes(include=np.number).columns.tolist()
    if c not in ODDS_COLS
]

# Categorical columns
categorical_columns = X_train.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Numerical columns (excluding odds):", len(numeric_columns))
print("Categorical columns:", len(categorical_columns))

Numerical columns (excluding odds): 67
Categorical columns: 13

In [23]:
# Numerical imputation values learned from training data (odds remain NaN)
numeric_fill_values = X_train[numeric_columns].median()

# Categorical imputation values learned from training data
categorical_fill_values = {
    col: X_train[col].mode(dropna=True)[0]
    for col in categorical_columns
    if X_train[col].notna().any()
}

In [24]:
# Apply numerical imputation (only to non-odds numeric columns)
for col in numeric_columns:
    X_train[col] = X_train[col].fillna(numeric_fill_values[col])
    X_val[col] = X_val[col].fillna(numeric_fill_values[col])
    X_test[col] = X_test[col].fillna(numeric_fill_values[col])

# Apply categorical imputation
for col, value in categorical_fill_values.items():
    X_train[col] = X_train[col].fillna(value)
    X_val[col] = X_val[col].fillna(value)
    X_test[col] = X_test[col].fillna(value)

Verify missing values after preprocessing

In [28]:
print("Remaining missing values")

print("\nTraining:")
print(X_train.isnull().sum().sum())

print("Validation:")
print(X_val.isnull().sum().sum())

print("Test:")
print(X_test.isnull().sum().sum())

Remaining missing values

Training:
115851
Validation:
41700
Test:
45909

Verify the target wasn't accidentally changed

In [29]:
print("Training target:")
display(y_train.value_counts())

print("\nValidation target:")
display(y_val.value_counts())

print("\nTest target:")
display(y_test.value_counts())

Training target:

target_outcome
Home Win    8433
Away Win    5126
Draw        4624
Name: count, dtype: int64

Validation target:

target_outcome
Home Win    1753
Away Win    1147
Draw         973
Name: count, dtype: int64

Test target:

target_outcome
Home Win    1731
Away Win    1193
Draw         999
Name: count, dtype: int64

Final preprocessing summary

In [30]:
preprocessing_summary = pd.DataFrame({
    "Dataset": [
        "Training",
        "Validation",
        "Test"
    ],
    "Rows": [
        len(X_train),
        len(X_val),
        len(X_test)
    ],
    "Columns": [
        X_train.shape[1],
        X_val.shape[1],
        X_test.shape[1]
    ],
    "Missing Values": [
        X_train.isnull().sum().sum(),
        X_val.isnull().sum().sum(),
        X_test.isnull().sum().sum()
    ]
})

display(preprocessing_summary)

      Dataset   Rows  Columns  Missing Values
0    Training  18183      111          115851
1  Validation   3873      111           41700
2        Test   3923      111           45909

In [31]:
# Final ID alignment verification

assert len(train_ids) == len(X_train) == len(y_train)
assert len(val_ids) == len(X_val) == len(y_val)
assert len(test_ids) == len(X_test) == len(y_test)

# Verify the preprocessing stage did not change row order
assert train_ids.reset_index(drop=True).equals(
    train_df["id"].reset_index(drop=True)
)

assert val_ids.reset_index(drop=True).equals(
    val_df["id"].reset_index(drop=True)
)

assert test_ids.reset_index(drop=True).equals(
    test_df["id"].reset_index(drop=True)
)

print("ID and row alignment verified before saving.")

ID and row alignment verified before saving.

In [32]:
# Verify raw odds kept their genuine missing rates
for c in ["SJH", "GBH", "BSH"]:
    print(c, "NaN rate:", X_train[c].isna().mean().round(3))

SJH NaN rate: 0.132
GBH NaN rate: 0.221
BSH NaN rate: 0.221

Save preprocessed dataset

In [ ]:
PREPROCESSED_DIR = os.path.join(
    BASE_DIR,
    "preprocessed_dataset"
)

os.makedirs(PREPROCESSED_DIR, exist_ok=True)

X_train.to_csv(
    os.path.join(PREPROCESSED_DIR, "X_train_preprocessed.csv"), index=False
)

X_val.to_csv(
    os.path.join(PREPROCESSED_DIR, "X_validation_preprocessed.csv"), index=False
)

X_test.to_csv(
    os.path.join(PREPROCESSED_DIR, "X_test_preprocessed.csv"), index=False
)

y_train.to_csv(
    os.path.join(PREPROCESSED_DIR, "y_train.csv"), index=False
)

y_val.to_csv(
    os.path.join(PREPROCESSED_DIR, "y_validation.csv"), index=False
)

y_test.to_csv(
    os.path.join(PREPROCESSED_DIR, "y_test.csv"), index=False
)

# Save match IDs separately

train_ids.rename("id").to_csv(
    os.path.join(
        PREPROCESSED_DIR,
        "train_ids.csv"
    ),
    index=False
)

val_ids.rename("id").to_csv(
    os.path.join(
        PREPROCESSED_DIR,
        "validation_ids.csv"
    ),
    index=False
)

test_ids.rename("id").to_csv(
    os.path.join(
        PREPROCESSED_DIR,
        "test_ids.csv"
    ),
    index=False
)

print("Preprocessed datasets saved to:")
print(PREPROCESSED_DIR)

print("\nFiles:")
print(os.listdir(PREPROCESSED_DIR))

Preprocessed datasets saved to:
/content/drive/MyDrive/ML Assignment/preprocessed_dataset

Files:
['X_train_preprocessed.csv', 'X_validation_preprocessed.csv', 'X_test_preprocessed.csv', 'y_train.csv', 'y_validation.csv', 'y_test.csv', 'train_ids.csv', 'validation_ids.csv', 'test_ids.csv']